using System;
using System.Collections.Generic;
using System.Linq;

namespace DS1ParamEditor
{
    public static class ItemData
    {
        public class Item
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public int CategoryId { get; set; }
            public Item(int id, string name, int categoryId) { Id = id; Name = name; CategoryId = categoryId; }
            public override string ToString() => $"[{Id}] {Name}";
        }

        public const int WEAPON = 0x00000000;
        public const int ARMOR  = 0x10000000;
        public const int RING   = 0x20000000;
        public const int GOODS  = 0x40000000;

        private static readonly Item[] Weapons = new[]
        {
            new Item( 100000, "Dagger", WEAPON),
            new Item( 101000, "Parrying Dagger", WEAPON),
            new Item( 102000, "Ghost Blade", WEAPON),
            new Item( 103000, "Bandit's Knife", WEAPON),
            new Item( 104000, "Priscilla's Dagger", WEAPON),
            new Item( 200000, "Shortsword", WEAPON),
            new Item( 201000, "Longsword", WEAPON),
            new Item( 202000, "Broadsword", WEAPON),
            new Item( 203000, "Broken Straight Sword", WEAPON),
            new Item( 204000, "Balder Side Sword", WEAPON),
            new Item( 205000, "Crystal Straight Sword", WEAPON),
            new Item( 206000, "Sunlight Straight Sword", WEAPON),
            new Item( 207000, "Barbed Straight Sword", WEAPON),
            new Item( 208000, "Silver Knight Straight Sword", WEAPON),
            new Item( 209000, "Astora's Straight Sword", WEAPON),
            new Item( 210000, "Darksword", WEAPON),
            new Item( 211000, "Drake Sword", WEAPON),
            new Item( 212000, "Straight Sword Hilt", WEAPON),
            new Item( 300000, "Bastard Sword", WEAPON),
            new Item( 301000, "Claymore", WEAPON),
            new Item( 302000, "Man-serpent Greatsword", WEAPON),
            new Item( 303000, "Flamberge", WEAPON),
            new Item( 304000, "Crystal Greatsword", WEAPON),
            new Item( 306000, "Stone Greatsword", WEAPON),
            new Item( 307000, "Greatsword of Artorias", WEAPON),
            new Item( 309000, "Moonlight Greatsword", WEAPON),
            new Item( 310000, "Black Knight Sword", WEAPON),
            new Item( 311000, "Greatsword of Artorias (Cursed)", WEAPON),
            new Item( 314000, "Great Lord Greatsword", WEAPON),
            new Item( 350000, "Zweihander", WEAPON),
            new Item( 351000, "Greatsword", WEAPON),
            new Item( 352000, "Demon Great Machete", WEAPON),
            new Item( 354000, "Dragon Greatsword", WEAPON),
            new Item( 355000, "Black Knight Greatsword", WEAPON),
            new Item( 400000, "Scimitar", WEAPON),
            new Item( 401000, "Falchion", WEAPON),
            new Item( 402000, "Shotel", WEAPON),
            new Item( 403000, "Jagged Ghost Blade", WEAPON),
            new Item( 405000, "Painting Guardian Sword", WEAPON),
            new Item( 406000, "Quelaag's Furysword", WEAPON),
            new Item( 450000, "Server", WEAPON),
            new Item( 451000, "Murakumo", WEAPON),
            new Item( 453000, "Gravelord Sword", WEAPON),
            new Item( 500000, "Uchigatana", WEAPON),
            new Item( 501000, "Washing Pole", WEAPON),
            new Item( 502000, "Iaito", WEAPON),
            new Item( 503000, "Chaos Blade", WEAPON),
            new Item( 600000, "Mail Breaker", WEAPON),
            new Item( 601000, "Rapier", WEAPON),
            new Item( 602000, "Estoc", WEAPON),
            new Item( 603000, "Velka's Rapier", WEAPON),
            new Item( 604000, "Ricard's Rapier", WEAPON),
            new Item( 700000, "Hand Axe", WEAPON),
            new Item( 701000, "Battle Axe", WEAPON),
            new Item( 702000, "Crescent Axe", WEAPON),
            new Item( 703000, "Butcher Knife", WEAPON),
            new Item( 704000, "Golem Axe", WEAPON),
            new Item( 705000, "Gargoyle Tail Axe", WEAPON),
            new Item( 750000, "Greataxe", WEAPON),
            new Item( 751000, "Demon's Greataxe", WEAPON),
            new Item( 752000, "Dragon King Greataxe", WEAPON),
            new Item( 753000, "Black Knight Greataxe", WEAPON),
            new Item( 800000, "Club", WEAPON),
            new Item( 801000, "Mace", WEAPON),
            new Item( 802000, "Morning Star", WEAPON),
            new Item( 803000, "Warpick", WEAPON),
            new Item( 804000, "Pickaxe", WEAPON),
            new Item( 809000, "Reinforced Club", WEAPON),
            new Item( 810000, "Blacksmith Hammer", WEAPON),
            new Item( 811000, "Blacksmith Giant Hammer", WEAPON),
            new Item( 812000, "Hammer of Vamos", WEAPON),
            new Item( 850000, "Great Club", WEAPON),
            new Item( 851000, "Grant", WEAPON),
            new Item( 852000, "Demon's Great Hammer", WEAPON),
            new Item( 854000, "Dragon Tooth", WEAPON),
            new Item( 855000, "Large Club", WEAPON),
            new Item( 856000, "Smough's Hammer", WEAPON),
            new Item( 901000, "Caestus", WEAPON),
            new Item( 902000, "Claw", WEAPON),
            new Item( 903000, "Dragon Bone Fist", WEAPON),
            new Item( 904000, "Dark Hand", WEAPON),
            new Item(1000000, "Spear", WEAPON),
            new Item(1001000, "Winged Spear", WEAPON),
            new Item(1002000, "Partizan", WEAPON),
            new Item(1003000, "Demon's Spear", WEAPON),
            new Item(1004000, "Channeler's Trident", WEAPON),
            new Item(1006000, "Silver Knight Spear", WEAPON),
            new Item(1050000, "Pike", WEAPON),
            new Item(1051000, "Dragonslayer Spear", WEAPON),
            new Item(1052000, "Moonlight Butterfly Horn", WEAPON),
            new Item(1100000, "Halberd", WEAPON),
            new Item(1101000, "Giant's Halberd", WEAPON),
            new Item(1102000, "Titanite Catch Pole", WEAPON),
            new Item(1103000, "Gargoyle's Halberd", WEAPON),
            new Item(1105000, "Black Knight Halberd", WEAPON),
            new Item(1106000, "Lucerne", WEAPON),
            new Item(1107000, "Scythe", WEAPON),
            new Item(1150000, "Great Scythe", WEAPON),
            new Item(1151000, "Lifehunt Scythe", WEAPON),
            new Item(1600000, "Whip", WEAPON),
            new Item(1601000, "Notched Whip", WEAPON),
            new Item(1200000, "Short Bow", WEAPON),
            new Item(1201000, "Longbow", WEAPON),
            new Item(1202000, "Black Bow of Pharis", WEAPON),
            new Item(1203000, "Dragonslayer Greatbow", WEAPON),
            new Item(1204000, "Composite Bow", WEAPON),
            new Item(1205000, "Darkmoon Bow", WEAPON),
            new Item(1250000, "Light Crossbow", WEAPON),
            new Item(1251000, "Heavy Crossbow", WEAPON),
            new Item(1252000, "Avelyn", WEAPON),
            new Item(1253000, "Sniper Crossbow", WEAPON),
            new Item(2000000, "Standard Arrow", WEAPON),
            new Item(2001000, "Large Arrow", WEAPON),
            new Item(2002000, "Feather Arrow", WEAPON),
            new Item(2003000, "Fire Arrow", WEAPON),
            new Item(2004000, "Poison Arrow", WEAPON),
            new Item(2005000, "Moonlight Arrow", WEAPON),
            new Item(2006000, "Wooden Arrow", WEAPON),
            new Item(2007000, "Dragonslayer Arrow", WEAPON),
            new Item(2008000, "Gough's Great Arrow", WEAPON),
            new Item(2100000, "Standard Bolt", WEAPON),
            new Item(2101000, "Heavy Bolt", WEAPON),
            new Item(2102000, "Sniper Bolt", WEAPON),
            new Item(2103000, "Wood Bolt", WEAPON),
            new Item(2104000, "Lightning Bolt", WEAPON),
            new Item(1396000, "Skull Lantern", WEAPON),
            new Item(1400000, "East-West Shield", WEAPON),
            new Item(1401000, "Wooden Shield", WEAPON),
            new Item(1402000, "Large Leather Shield", WEAPON),
            new Item(1403000, "Small Leather Shield", WEAPON),
            new Item(1404000, "Target Shield", WEAPON),
            new Item(1405000, "Buckler", WEAPON),
            new Item(1406000, "Cracked Round Shield", WEAPON),
            new Item(1408000, "Leather Shield", WEAPON),
            new Item(1409000, "Plank Shield", WEAPON),
            new Item(1410000, "Caduceus Round Shield", WEAPON),
            new Item(1411000, "Crystal Ring Shield", WEAPON),
            new Item(1450000, "Heater Shield", WEAPON),
            new Item(1451000, "Knight Shield", WEAPON),
            new Item(1452000, "Tower Kite Shield", WEAPON),
            new Item(1453000, "Grass Crest Shield", WEAPON),
            new Item(1454000, "Hollow Soldier Shield", WEAPON),
            new Item(1455000, "Balder Shield", WEAPON),
            new Item(1456000, "Crest Shield", WEAPON),
            new Item(1457000, "Dragon Crest Shield", WEAPON),
            new Item(1460000, "Warrior's Round Shield", WEAPON),
            new Item(1461000, "Iron Round Shield", WEAPON),
            new Item(1462000, "Spider Shield", WEAPON),
            new Item(1470000, "Spiked Shield", WEAPON),
            new Item(1471000, "Crystal Shield", WEAPON),
            new Item(1472000, "Sunlight Shield", WEAPON),
            new Item(1473000, "Silver Knight Shield", WEAPON),
            new Item(1474000, "Black Knight Shield", WEAPON),
            new Item(1475000, "Pierce Shield", WEAPON),
            new Item(1476000, "Red and White Round Shield", WEAPON),
            new Item(1477000, "Caduceus Kite Shield", WEAPON),
            new Item(1478000, "Gargoyle's Shield", WEAPON),
            new Item(1500000, "Eagle Shield", WEAPON),
            new Item(1501000, "Tower Shield", WEAPON),
            new Item(1502000, "Giant Shield", WEAPON),
            new Item(1503000, "Stone Greatshield", WEAPON),
            new Item(1505000, "Havel's Greatshield", WEAPON),
            new Item(1506000, "Bonewheel Shield", WEAPON),
            new Item(1507000, "Greatshield of Artorias", WEAPON),
            new Item(1300000, "Sorcerer's Catalyst", WEAPON),
            new Item(1301000, "Beatrice's Catalyst", WEAPON),
            new Item(1302000, "Tin Banishment Catalyst", WEAPON),
            new Item(1303000, "Logan's Catalyst", WEAPON),
            new Item(1304000, "Tin Darkmoon Catalyst", WEAPON),
            new Item(1305000, "Oolacile Ivory Catalyst", WEAPON),
            new Item(1306000, "Tin Crystallization Catalyst", WEAPON),
            new Item(1307000, "Demon's Catalyst", WEAPON),
            new Item(1308000, "Izalith Catalyst", WEAPON),
            new Item(1330000, "Pyromancy Flame", WEAPON),
            new Item(1332000, "Pyromancy Flame (Ascended)", WEAPON),
            new Item(1360000, "Talisman", WEAPON),
            new Item(1361000, "Canvas Talisman", WEAPON),
            new Item(1362000, "Thorolund Talisman", WEAPON),
            new Item(1363000, "Ivory Talisman", WEAPON),
            new Item(1365000, "Sunlight Talisman", WEAPON),
            new Item(1366000, "Darkmoon Talisman", WEAPON),
            new Item(1367000, "Velka's Talisman", WEAPON),
            new Item(9000000, "Effigy Shield", WEAPON),
            new Item(9001000, "Sanctus", WEAPON),
            new Item(9002000, "Bloodshield", WEAPON),
            new Item(9003000, "Black Iron Greatshield", WEAPON),
            new Item(9010000, "Gold Tracer", WEAPON),
            new Item(9011000, "Dark Silver Tracer", WEAPON),
            new Item(9012000, "Abyss Greatsword", WEAPON),
            new Item(9014000, "Cleansing Greatshield", WEAPON),
            new Item(9015000, "Stone Greataxe", WEAPON),
            new Item(9016000, "Four-pronged Plow", WEAPON),
            new Item(9017000, "Manus Catalyst", WEAPON),
            new Item(9018000, "Oolacile Catalyst", WEAPON),
            new Item(9019000, "Guardian Tail", WEAPON),
            new Item(9020000, "Obsidian Greatsword", WEAPON),
            new Item(9021000, "Gough's Greatbow", WEAPON),
        };

        private static readonly Item[] Armor = new[]
        {
            new Item( 10000, "Catarina Helm", ARMOR), new Item( 11000, "Catarina Armor", ARMOR), new Item( 12000, "Catarina Gauntlets", ARMOR), new Item( 13000, "Catarina Leggings", ARMOR),
            new Item( 40000, "Dark Mask", ARMOR), new Item( 41000, "Dark Armor", ARMOR), new Item( 42000, "Dark Gauntlets", ARMOR), new Item( 43000, "Dark Leggings", ARMOR),
            new Item( 50000, "Brigand Hood", ARMOR), new Item( 51000, "Brigand Armor", ARMOR), new Item( 52000, "Brigand Gauntlets", ARMOR), new Item( 53000, "Brigand Trousers", ARMOR),
            new Item( 60000, "Shadow Mask", ARMOR), new Item( 61000, "Shadow Garb", ARMOR), new Item( 62000, "Shadow Gauntlets", ARMOR), new Item( 63000, "Shadow Leggings", ARMOR),
            new Item( 70000, "Black Iron Helm", ARMOR), new Item( 71000, "Black Iron Armor", ARMOR), new Item( 72000, "Black Iron Gauntlets", ARMOR), new Item( 73000, "Black Iron Leggings", ARMOR),
            new Item( 80000, "Smough's Helm", ARMOR), new Item( 81000, "Smough's Armor", ARMOR), new Item( 82000, "Smough's Gauntlets", ARMOR), new Item( 83000, "Smough's Leggings", ARMOR),
            new Item(100000, "Helm of Favor", ARMOR), new Item(101000, "Embraced Armor of Favor", ARMOR), new Item(102000, "Gauntlets of Favor", ARMOR), new Item(103000, "Leggings of Favor", ARMOR),
            new Item(120000, "Stone Helm", ARMOR), new Item(121000, "Stone Armor", ARMOR), new Item(122000, "Stone Gauntlets", ARMOR), new Item(123000, "Stone Leggings", ARMOR),
            new Item(140000, "Mask of the Sealer", ARMOR), new Item(141000, "Crimson Robe", ARMOR), new Item(142000, "Crimson Gloves", ARMOR), new Item(143000, "Crimson Waistcloth", ARMOR),
            new Item(160000, "Iron Helm", ARMOR), new Item(161000, "Armor of the Sun", ARMOR), new Item(162000, "Iron Bracelet", ARMOR), new Item(163000, "Iron Leggings", ARMOR),
            new Item(170000, "Chain Helm", ARMOR), new Item(171000, "Chain Armor", ARMOR), new Item(172000, "Leather Gauntlets", ARMOR), new Item(173000, "Chain Leggings", ARMOR),
            new Item(200000, "Helm of Thorns", ARMOR), new Item(201000, "Armor of Thorns", ARMOR), new Item(202000, "Gauntlets of Thorns", ARMOR), new Item(203000, "Leggings of Thorns", ARMOR),
            new Item(210000, "Standard Helm", ARMOR), new Item(211000, "Hard Leather Armor", ARMOR), new Item(212000, "Hard Leather Gauntlets", ARMOR), new Item(213000, "Hard Leather Boots", ARMOR),
            new Item(220000, "Sorcerer Hat", ARMOR), new Item(221000, "Sorcerer Cloak", ARMOR), new Item(222000, "Sorcerer Gauntlets", ARMOR), new Item(223000, "Sorcerer Boots", ARMOR),
            new Item(240000, "Pharis's Hat", ARMOR), new Item(241000, "Leather Armor", ARMOR), new Item(242000, "Leather Gloves", ARMOR), new Item(243000, "Leather Boots", ARMOR),
            new Item(250000, "Painting Guardian Hood", ARMOR), new Item(251000, "Painting Guardian Robe", ARMOR), new Item(252000, "Painting Guardian Gloves", ARMOR), new Item(253000, "Painting Guardian Waistcloth", ARMOR),
            new Item(270000, "Ornstein's Helm", ARMOR), new Item(271000, "Ornstein's Armor", ARMOR), new Item(272000, "Ornstein's Gauntlets", ARMOR), new Item(273000, "Ornstein's Leggings", ARMOR),
            new Item(280000, "Eastern Helm", ARMOR), new Item(281000, "Eastern Armor", ARMOR), new Item(282000, "Eastern Gauntlets", ARMOR), new Item(283000, "Eastern Leggings", ARMOR),
            new Item(290000, "Xanthous Crown", ARMOR), new Item(291000, "Xanthous Overcoat", ARMOR), new Item(292000, "Xanthous Gloves", ARMOR), new Item(293000, "Xanthous Waistcloth", ARMOR),
            new Item(300000, "Thief Mask", ARMOR), new Item(301000, "Black Leather Armor", ARMOR), new Item(302000, "Black Leather Gloves", ARMOR), new Item(303000, "Black Leather Boots", ARMOR),
            new Item(320000, "Black Knight Helm", ARMOR), new Item(321000, "Black Knight Armor", ARMOR), new Item(322000, "Black Knight Gauntlets", ARMOR), new Item(323000, "Black Knight Leggings", ARMOR),
            new Item(330000, "Crown of Dusk", ARMOR), new Item(331000, "Antiquated Dress", ARMOR), new Item(332000, "Antiquated Gloves", ARMOR), new Item(333000, "Antiquated Skirt", ARMOR),
            new Item(350000, "Elite Knight Helm", ARMOR), new Item(351000, "Elite Knight Armor", ARMOR), new Item(352000, "Elite Knight Gauntlets", ARMOR), new Item(353000, "Elite Knight Leggings", ARMOR),
            new Item(360000, "Wanderer Hood", ARMOR), new Item(361000, "Wanderer Coat", ARMOR), new Item(362000, "Wanderer Manchette", ARMOR), new Item(363000, "Wanderer Boots", ARMOR),
            new Item(380000, "Big Hat", ARMOR), new Item(381000, "Sage Robe", ARMOR), new Item(382000, "Traveling Gloves", ARMOR), new Item(383000, "Traveling Boots", ARMOR),
            new Item(390000, "Knight Helm", ARMOR), new Item(391000, "Knight Armor", ARMOR), new Item(392000, "Knight Gauntlets", ARMOR), new Item(393000, "Knight Leggings", ARMOR),
            new Item(420000, "Silver Knight Helm", ARMOR), new Item(421000, "Silver Knight Armor", ARMOR), new Item(422000, "Silver Knight Gauntlets", ARMOR), new Item(423000, "Silver Knight Leggings", ARMOR),
            new Item(440000, "Havel's Helm", ARMOR), new Item(441000, "Havel's Armor", ARMOR), new Item(442000, "Havel's Gauntlets", ARMOR), new Item(443000, "Havel's Leggings", ARMOR),
            new Item(450000, "Brass Helm", ARMOR), new Item(451000, "Brass Armor", ARMOR), new Item(452000, "Brass Gauntlets", ARMOR), new Item(453000, "Brass Leggings", ARMOR),
            new Item(460000, "Gold-Hemmed Black Hood", ARMOR), new Item(461000, "Gold-Hemmed Black Cloak", ARMOR), new Item(462000, "Gold-Hemmed Black Gloves", ARMOR), new Item(463000, "Gold-Hemmed Black Skirt", ARMOR),
            new Item(470000, "Golem Helm", ARMOR), new Item(471000, "Golem Armor", ARMOR), new Item(472000, "Golem Gauntlets", ARMOR), new Item(473000, "Golem Leggings", ARMOR),
            new Item(490000, "Steel Helm", ARMOR), new Item(491000, "Steel Armor", ARMOR), new Item(492000, "Steel Gauntlets", ARMOR), new Item(493000, "Steel Leggings", ARMOR),
            new Item(510000, "Balder Helm", ARMOR), new Item(511000, "Balder Armor", ARMOR), new Item(512000, "Balder Gauntlets", ARMOR), new Item(513000, "Balder Leggings", ARMOR),
            new Item(530000, "Giant Helm", ARMOR), new Item(531000, "Giant Armor", ARMOR), new Item(532000, "Giant Gauntlets", ARMOR), new Item(533000, "Giant Leggings", ARMOR),
            new Item(540000, "Crown of the Dark Sun", ARMOR), new Item(541000, "Moonlight Robe", ARMOR), new Item(542000, "Moonlight Gloves", ARMOR), new Item(543000, "Moonlight Waistcloth", ARMOR),
            new Item(550000, "Crown of the Great Lord", ARMOR), new Item(551000, "Robe of the Great Lord", ARMOR), new Item(552000, "Bracelet of the Great Lord", ARMOR), new Item(553000, "Anklet of the Great Lord", ARMOR),
            new Item(560000, "Sack", ARMOR), new Item(570000, "Symbol of Avarice", ARMOR), new Item(580000, "Royal Helm", ARMOR),
            new Item(590000, "Mask of the Father", ARMOR), new Item(600000, "Mask of the Mother", ARMOR), new Item(610000, "Mask of the Child", ARMOR),
            new Item(620000, "Fang Boar Helm", ARMOR), new Item(630000, "Gargoyle Helm", ARMOR),
            new Item(640000, "Black Sorcerer Hat", ARMOR), new Item(641000, "Black Sorcerer Cloak", ARMOR), new Item(642000, "Black Sorcerer Gauntlets", ARMOR), new Item(643000, "Black Sorcerer Boots", ARMOR),
            new Item(660000, "Helm of Artorias", ARMOR), new Item(661000, "Armor of Artorias", ARMOR), new Item(662000, "Gauntlets of Artorias", ARMOR), new Item(663000, "Leggings of Artorias", ARMOR),
            new Item(670000, "Porcelain Mask", ARMOR), new Item(671000, "Lord's Blade Robe", ARMOR), new Item(672000, "Lord's Blade Gloves", ARMOR), new Item(673000, "Lord's Blade Waistcloth", ARMOR),
            new Item(680000, "Gough's Helm", ARMOR), new Item(681000, "Gough's Armor", ARMOR), new Item(682000, "Gough's Gauntlets", ARMOR), new Item(683000, "Gough's Leggings", ARMOR),
            new Item(700000, "Snickering Top Hat", ARMOR), new Item(701000, "Chester's Long Coat", ARMOR), new Item(702000, "Chester's Gloves", ARMOR), new Item(703000, "Chester's Trousers", ARMOR),
        };

        private static readonly Item[] Rings = new[]
        {
            new Item(100, "Havel's Ring", RING), new Item(101, "Red Tearstone Ring", RING), new Item(102, "Darkmoon Blade Covenant Ring", RING),
            new Item(103, "Cat Covenant Ring", RING), new Item(104, "Cloranthy Ring", RING), new Item(105, "Flame Stoneplate Ring", RING),
            new Item(106, "Thunder Stoneplate Ring", RING), new Item(107, "Spell Stoneplate Ring", RING), new Item(108, "Speckled Stoneplate Ring", RING),
            new Item(109, "Bloodbite Ring", RING), new Item(110, "Poisonbite Ring", RING), new Item(111, "Tiny Being's Ring", RING),
            new Item(113, "Cursebite Ring", RING), new Item(114, "White Seance Ring", RING), new Item(115, "Bellowing Dragoncrest Ring", RING),
            new Item(116, "Dusk Crown Ring", RING), new Item(117, "Hornet Ring", RING), new Item(119, "Hawk Ring", RING),
            new Item(120, "Ring of Steel Protection", RING), new Item(121, "Covetous Gold Serpent Ring", RING), new Item(122, "Covetous Silver Serpent Ring", RING),
            new Item(123, "Slumbering Dragoncrest Ring", RING), new Item(124, "Ring of Fog", RING), new Item(125, "Rusted Iron Ring", RING),
            new Item(126, "Ring of Sacrifice", RING), new Item(127, "Rare Ring of Sacrifice", RING), new Item(128, "Dark Wood Grain Ring", RING),
            new Item(130, "Ring of the Sun Princess", RING), new Item(137, "Old Witch's Ring", RING), new Item(138, "Covenant of Artorias", RING),
            new Item(139, "Orange Charred Ring", RING), new Item(141, "Lingering Dragoncrest Ring", RING), new Item(142, "Ring of the Evil Eye", RING),
            new Item(143, "Ring of Favor and Protection", RING), new Item(144, "Leo Ring", RING), new Item(145, "East Wood Grain Ring", RING),
            new Item(146, "Wolf Ring", RING), new Item(147, "Blue Tearstone Ring", RING), new Item(148, "Ring of the Sun's Firstborn", RING),
            new Item(149, "Darkmoon Seance Ring", RING), new Item(150, "Calamity Ring", RING),
        };

        private static readonly Item[] Goods = new[]
        {
            new Item(109, "Eye of Death", GOODS), new Item(111, "Cracked Red Eye Orb", GOODS),
            new Item(230, "Elizabeth's Mushroom", GOODS), new Item(240, "Divine Blessing", GOODS), new Item(260, "Green Blossom", GOODS),
            new Item(270, "Bloodred Moss Clump", GOODS), new Item(271, "Purple Moss Clump", GOODS), new Item(272, "Blooming Purple Moss Clump", GOODS),
            new Item(274, "Purging Stone", GOODS), new Item(275, "Egg Vermifuge", GOODS), new Item(280, "Repair Powder", GOODS),
            new Item(290, "Throwing Knife", GOODS), new Item(291, "Poison Throwing Knife", GOODS), new Item(292, "Firebomb", GOODS),
            new Item(293, "Dung Pie", GOODS), new Item(294, "Alluring Skull", GOODS), new Item(296, "Lloyd's Talisman", GOODS),
            new Item(297, "Black Firebomb", GOODS), new Item(310, "Charcoal Pine Resin", GOODS), new Item(311, "Gold Pine Resin", GOODS),
            new Item(312, "Transient Curse", GOODS), new Item(313, "Rotten Pine Resin", GOODS), new Item(330, "Homeward Bone", GOODS),
            new Item(370, "Prism Stone", GOODS), new Item(374, "Souvenir of Reprisal", GOODS), new Item(375, "Sunlight Medal", GOODS),
            new Item(376, "Pendant", GOODS), new Item(380, "Rubbish", GOODS),
            new Item(400, "Soul of a Lost Undead", GOODS), new Item(401, "Large Soul of a Lost Undead", GOODS),
            new Item(402, "Soul of a Nameless Soldier", GOODS), new Item(403, "Large Soul of a Nameless Soldier", GOODS),
            new Item(404, "Soul of a Proud Knight", GOODS), new Item(405, "Large Soul of a Proud Knight", GOODS),
            new Item(406, "Soul of a Brave Warrior", GOODS), new Item(407, "Large Soul of a Brave Warrior", GOODS),
            new Item(408, "Soul of a Hero", GOODS), new Item(409, "Soul of a Great Hero", GOODS),
            new Item(500, "Humanity", GOODS), new Item(501, "Twin Humanities", GOODS),
            new Item(700, "Soul of Quelaag", GOODS), new Item(701, "Soul of Sif", GOODS), new Item(702, "Soul of Gwyn, Lord of Cinder", GOODS),
            new Item(703, "Core of an Iron Golem", GOODS), new Item(704, "Soul of Ornstein", GOODS), new Item(705, "Soul of the Moonlight Butterfly", GOODS),
            new Item(706, "Soul of Smough", GOODS), new Item(707, "Soul of Priscilla", GOODS), new Item(708, "Soul of Gwyndolin", GOODS),
            new Item(709, "Guardian Soul", GOODS), new Item(710, "Soul of Artorias", GOODS), new Item(711, "Soul of Manus", GOODS),
            new Item(800, "Large Ember", GOODS), new Item(801, "Very Large Ember", GOODS), new Item(802, "Crystal Ember", GOODS),
            new Item(808, "Divine Ember", GOODS), new Item(809, "Large Divine Ember", GOODS), new Item(810, "Dark Ember", GOODS),
            new Item(812, "Large Flame Ember", GOODS), new Item(813, "Chaos Flame Ember", GOODS),
            new Item(1000, "Titanite Shard", GOODS), new Item(1010, "Large Titanite Shard", GOODS), new Item(1020, "Green Titanite Shard", GOODS),
            new Item(1030, "Titanite Chunk", GOODS), new Item(1040, "Blue Titanite Chunk", GOODS), new Item(1050, "White Titanite Chunk", GOODS),
            new Item(1060, "Red Titanite Chunk", GOODS), new Item(1070, "Titanite Slab", GOODS), new Item(1080, "Blue Titanite Slab", GOODS),
            new Item(1090, "White Titanite Slab", GOODS), new Item(1100, "Red Titanite Slab", GOODS),
            new Item(1110, "Dragon Scale", GOODS), new Item(1120, "Demon Titanite", GOODS), new Item(1130, "Twinkling Titanite", GOODS),
            new Item(100, "White Sign Soapstone", GOODS), new Item(101, "Red Sign Soapstone", GOODS), new Item(102, "Red Eye Orb", GOODS),
            new Item(106, "Orange Guidance Soapstone", GOODS), new Item(113, "Blue Eye Orb", GOODS), new Item(114, "Dragon Eye", GOODS),
            new Item(117, "Darksign", GOODS), new Item(220, "Silver Pendant", GOODS), new Item(371, "Binoculars", GOODS),
            new Item(377, "Dragon Head Stone", GOODS), new Item(378, "Dragon Torso Stone", GOODS), new Item(385, "Dried Finger", GOODS),
            new Item(2001, "Basement Key", GOODS), new Item(2002, "Crest of Artorias", GOODS), new Item(2007, "Blighttown Key", GOODS),
            new Item(2008, "Key to New Londo Ruins", GOODS), new Item(2013, "Key to the Seal", GOODS), new Item(2014, "Key to Depths", GOODS),
            new Item(2100, "Master Key", GOODS), new Item(2510, "Lordvessel", GOODS),
            new Item(2600, "Weapon Smithbox", GOODS), new Item(2601, "Armor Smithbox", GOODS), new Item(2602, "Repairbox", GOODS),
            new Item(2607, "Rite of Kindling", GOODS), new Item(2608, "Bottomless Box", GOODS),
            new Item(3000, "Sorcery: Soul Arrow", GOODS), new Item(3010, "Sorcery: Great Soul Arrow", GOODS),
            new Item(3060, "Sorcery: Soul Spear", GOODS), new Item(3100, "Sorcery: Magic Weapon", GOODS),
            new Item(3110, "Sorcery: Great Magic Weapon", GOODS), new Item(3120, "Sorcery: Crystal Magic Weapon", GOODS),
            new Item(3700, "Sorcery: White Dragon Breath", GOODS), new Item(3710, "Sorcery: Dark Orb", GOODS),
            new Item(4000, "Pyromancy: Fireball", GOODS), new Item(4020, "Pyromancy: Great Fireball", GOODS),
            new Item(4030, "Pyromancy: Firestorm", GOODS), new Item(4100, "Pyromancy: Combustion", GOODS),
            new Item(4110, "Pyromancy: Great Combustion", GOODS), new Item(4300, "Pyromancy: Iron Flesh", GOODS),
            new Item(4310, "Pyromancy: Flash Sweat", GOODS), new Item(4400, "Pyromancy: Power Within", GOODS),
            new Item(4500, "Pyromancy: Great Chaos Fireball", GOODS), new Item(4510, "Pyromancy: Chaos Storm", GOODS),
            new Item(5000, "Miracle: Heal", GOODS), new Item(5010, "Miracle: Great Heal", GOODS),
            new Item(5030, "Miracle: Soothing Sunlight", GOODS), new Item(5040, "Miracle: Replenishment", GOODS),
            new Item(5210, "Miracle: Homeward", GOODS), new Item(5300, "Miracle: Force", GOODS),
            new Item(5310, "Miracle: Wrath of the Gods", GOODS), new Item(5500, "Miracle: Lightning Spear", GOODS),
            new Item(5510, "Miracle: Great Lightning Spear", GOODS), new Item(5520, "Miracle: Sunlight Spear", GOODS),
            new Item(5900, "Miracle: Sunlight Blade", GOODS), new Item(5910, "Miracle: Darkmoon Blade", GOODS),
        };

        public static readonly Item[] AllItems;

        static ItemData()
        {
            AllItems = Weapons.Concat(Armor).Concat(Rings).Concat(Goods).OrderBy(i => i.Name).ToArray();
        }

        public static Item[] GetItemsByCategory(int categoryId)
        {
            return AllItems.Where(i => i.CategoryId == categoryId).ToArray();
        }

        public static Item? FindItem(int categoryId, int itemId)
        {
            return AllItems.FirstOrDefault(i => i.CategoryId == categoryId && i.Id == itemId);
        }
    }
}
