name: Build

on:
  push:
    branches: [master]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: DS1ParamEditor

      - name: Checkout SoulsFormatsNEXT
        uses: actions/checkout@v4
        with:
          repository: soulsmods/SoulsFormatsNEXT
          path: SoulsFormatsNEXT

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Build SoulsFormatsNEXT
        run: dotnet build SoulsFormatsNEXT/SoulsFormats/SoulsFormats.csproj -c Release

      - run: dotnet build DS1ParamEditor/DS1DinamicParamEditor/DS1DinamicParamEditor.csproj -c Release

      - uses: actions/upload-artifact@v4
        with:
          name: DS1DPE
          path: DS1ParamEditor/DS1DinamicParamEditor/bin/Release/net9.0-windows/

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            DS1ParamEditor/DS1DinamicParamEditor/bin/Release/net9.0-windows/DS1DPE.exe
